project:
  type: website

website:
  title: "P. M. Thompson"
  navbar:
    right:
      - about.qmd
      - cv.qmd
      - software.qmd
      - icon: github
        href: https://github.com/paulmthompson

format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

