
#+TITLE: Leaky Competing Accumulator Model

* Definition
This is one of several types of perceptual decision making models
[TOPIC].

* Overview

A *stochastic accumulator* is a unit which can be characterized by its
*activation*, A, and its *output firing rate*, f. The *threshold
linear function* is f=A when A>=0 and f=0 when A<0. 

*Reaction Time* is defined as the time it takes to reach some
predefined criteon. In \cite{Zandbelt2014}, this is definted the sum
of 1. stimulus encoding stage (fixed duration and all accumulators set
equal to zero) 2. accumulation stage when A increased toward \theta
until *termination criteria* was met; and 3. response-executation stage
of fixed value.

In \cite{Zandbelt2014} they consider two possible kinds of termination
criteria: where a certain proportion of accumulators have crossed a
threshold of activity, or where the average firing rate is greater
than threshold.

Variability is seen in reaction times so the mechanism must have some
randomness to it. This has been described as either being a  *variable
rate model*, where different neurons reach threshold at different
rates, or a *variable threshold model*, where neurons have different
thresholds that trigger activation.

\begin{align}

dA(t) = (v - k A(t)) \frac{dt}{\tau} + \epsilon \sqrt{\frac{dt}{\tau}} 

\end{align}

A is activation

v accumulation rate

k leakage constant

\epsilon is Gaussian noise with zero mean and variance \sigma^2

\tau is a time scale time constant that makes calculations
convenient. so try to pick a dt/\tau that makes numerical calculations
easy (around 0.1)

\theta (not in the equation) is the threshold of the accumulator

Unknowns are threshold, \theta, the accumlation constant, v, and the leakage constant k.

* Experiments

** Lecas 1986

** Hanes 1996

** Usher 2001

** Zandbelt 2014

* Experimental Design

Background noise affecting accumulators rather than setting them equal
to zero?

Where does the go signal come from? Is it in multiple places at once?

Unscented Kalman filter to estimate state (monkey behavioral thing)
