
#+TITLE: Linearization

* Definition

Linearization is the process of taking equation(s) governing a
nonlinear system and approximating them as linear equations.

* Overview

* Example

The area of a circle is represented the equation
\begin{equation}
A = \pi*r^2
\end{equation}

We can represent the nonlinearity to a small change in area \delta(A)
to a small change in radius \delta(r) the following way:
\begin{equation}
A_0 + \delta(A) = \pi (r_0 + \delta(r))^2 = \pi (r_0^2 + 2 r_0
\delta(r) + \delta(r)^2)
\end{equation}

We can substract our normal area equation to show what \delta(A)
depends on

\begin{equation}
\delta(A) = \pi (2 r_0 \delta(r) + \delta(r)^2)
\end{equation}

So we see that a small change in area is dependant on both a linear (2
r_0 \delta(r)) term and a nonlinear (\delta(r)^2) term. Therefore, we
can linearize this equation by discarding the nonlinear term.

\begin{equation}
\delta(A) = 2 \pi r_0 \delta(r)
\begin{equation}

We see from above that the accuracy of our approximation will then
depend on 1) the size of the change in r; and 2) the distance from
r_0. For this reason, linearization is often refered to as being taken
"about a point" and the point that is selected can be critical.

* Taylor Series

Note that the derivation above is equivalent to the expanded Taylor
series discarding the higher order terms.

\begin{align}
A(r) &= f(a) + f'(a)(r-a) + ... \\
&= f(r_0) + f'(r_0)(r-r_0) \\
&= \pi r_0^2 + 2 \pi r_0 (r-r_0) \\
&= \pi r_0^2 + 2 \pi r_0 r - 2 \pi r_0^2 \\
&= 2 \pi r_0 r - \pi r_0^2
\end{align}

If this was evaluated at r= r_0 + \delta(r), we would have the same
result of above
