
#+TITLE: Corticomotor Neurons

* Definition

These are neurons that descend from the motor regions of the brain  to synapse on motor neurons in the ventral horn. They are therefore *monosynaptic* in the connections they made to the motor pool

* Evolution

Corticomotor neurons do not exist in non-primates, and are found with increasing numbers from monkeys to apes to humans.

* Organization

The CM pathway can be thought of as a division of the corticospinal tract. Some innervate only a single muscle motor pool, but many innervate multiple muscles that span continguous limb joints

The CM cell bodies are mostly found in caudal M1 by the central sulcus \cite{Rathelot2009}

* Function

The CM pathway mainly controls hand function, and its presence in greatly numbers with increasingly dexterous species probably indicates that it is a late evolutionary development for this purpose. 

Most synapses are weak so that they do not produce strong muscle movements themselves, but increase the probability of firing.

There is some evidence that this pathway is involved in locomotion.

* Reviews

\cite{Lemon2008} Discusses the different descending motor pathways across species

\cite{Alstermark2012} Focuses on spinal interneurons involved in reaching and grasping

#+BIBLIOGRAPHY: library plain option:--no-keywords option:--no-abstract limit:t




