
#+TITLE: Motor Learning

* TODO Behavioral Experiments of Motor Learning
* Definition

* Overview, Themes and Concepts

The gross structure of the motor cortex is fixed; however, subregions
vary between inviduals, indicating that they probably change over
time. 

The mechanism for this change probably has to do with
*horizontal fibers* than run from region to region that can be
modulated after the release of *local inhibitory circuits*.

Sensation plays a major role in motor learning because it gathers information related to whatever motor plan is being made/executed.

* Areas Implicated
** M1
*** Architecture

M1 has a gross somatotopy, but each region has distributed
networks. This allows for additional flexibility for modification.

Fibers that are most likely the modifiable components that implement
plasticity are the *horizontal fibers* running between different
regions. 

*** Mechanism

Some version of LTD and LTD are probably at work. In M1, there appears
to be extrinsic activiation/inhibition necessary to make an environment where LTP can occur. *Cerebello-thalamocortical* fibers
might serve this purpose. \cite{Sanes2000}

*** Experimental Evidence
\cite{Donoghue1987} Removed a limb from rats at birth and showed that
mapping of M1 was different such that limb was not represented in the
usual area, but other body parts had expanded to that region.

\cite{Sanes1988} Building of of work above, wanted to see if this kind
of plasticity extended into adulthood or exhibited a critical period
type of effect. Transected the facial nerve in adult rats and saw that
within *hours* the representation from other areas expanded into
cortex originally responsible for that nerve

\cite{Jacobs1991} Continuing to build from above, they wanted to
investigate the mechanism that lead to local plasticity. Cortical representations of areas were able to
expand after the *release of inhibitory circuits*. 

\cite{Nudo1996} After training, area that represented movement
expanded to stimulation in the cortex. Proressive and reversible
expansion was shown (as well of contraction of nearby areas unrelated
to the task). *More changes in rostral M1 compared to caudal*

** Cerebellum

* Types of Motor Learning
** Overview

There are multiple models of motor learning which can be divided by
mechanism. Error based learning will modify future movements based on
the error of previous movements, reinforcement learning will consider
complex concepts like reward, and use dependent learning will occur as
a result of doing something over and over again. All of these can
occur in parallel.

** Error-Based Learning
*** Mechanisms

**** Feedback-error Learning

[[../FeedbackControl.html][Feedback]] from the action is used to correct the action while it is
ongoing as well as alter feedback for the next action.

**** Supervised Learning

This type of learning makes adaptations of *internal models* based on 
[[../FeedforwardControl.html][predictions]] of the intended movement and desired outcome.

*** Experimental Evidence

\cite{Shadmehr1994} - Begins by explaining how distorting what is seen
by the subject by prism glasses affects kinematics of task, while
their approach of using a force field against the moving hand affects
the dynamics of the task. Their task showed adaptation over trials,
and *after effects* when the force field was removed.

\cite{Gandolfo2000} - Recorded from a monkey when it did a similar
task as above. Found several different cell types: *kinematic* cells
did not change activity, *memory* cells changed activity and continued
to be changed during washout, and other *dynamic* cells changed their activity during
the force field but went back to baseline.

\cite{Li2001} - 

** Reinforcement Learning 

*** Mechanism

This type of learning considers complex concepts such as "reward" to
shape motor plans rather than error. 

*** Experimental Evidence

** Use Dependent Learning

*** Mechanism

Occurs as a result of repetitive movements. May occur in parallel to
error based learning 

*** Experimental Evidence

* Models of Learning

** Internal Model Concept


** Types of Internal Models

*** Mechanistic Model

A *Motor Primitive* is a concept that represents a packet of neural information that can be combined with other primitives to generate behaviors.

It has been suggested that learning can take place by differentially combining motor primitives to change the outcome of a task \cite{Thoroughman2000}

*** Normative Model

*Credit Assignment*

*Dual rate model*

* Critical Experiments



* Reviews

\cite{Wolpert2011} 

\cite{Franklin2011} Considers the concepts of Bayesian Decision Theory, Optimal Feedback Control, Forward Models, Impendence control and motor learning

\cite{Shmuelof2011} Evolutionary History

\cite{Sanes2000} Focus on Plasticity Mechanisms

\cite{Dayan2002a} Reinforcement Learning

#+BIBLIOGRAPHY: library  plain option:--no-keywords option:--no-abstract limit:t
