
#+TITLE: Population Vector

* Definition

A population vector is generated by the sum of firing rates from individual neurons, which each  have unique [[../TuningCurve.html][tuning curves]]. If each neuron is modeled as a vector with its direction pointing in the preferred direction and the length of the vector dictated by the mean firing rate, the sum of individual neurons firing at different rates due to their own tuning characteristics will result in a vector sum which points in the direction of the movement being executed.

* Overview

This population vector theory can explain why one cortical neuron can be related to multiple muscles. One neuron can be part of multiple "groups" and can contribute to each group with a different weight.

* Experimental Evidence

This was first hypothesized by Georgopoulos in 1983, and later generalized to 3D coordinates
\cite{Georgopoulos1986} - prelim data of 3D
\cite{Schwartz1988} - 3D tuning curve data
\cite{Georgopoulos1988} - 3D population vector
\cite{Kettner1988} encode the same movement with a different origin. The baseline firing rates of cells will change, but the relationship between the movement direction and population vector will be similar

* Reviews

\cite{Schwartz2007} Good overview by one of the major scientists behind population vector theory

\cite{Kalaska2009} Excellent and very comprehensive book chapter detailing the connection between the motor cortex and reaching.

#+BIBLIOGRAPHY: library plain option:--no-keywords option:--no-abstract limit:t

